#!/usr/bin/env bash

if [ $# -eq 0 ]
then
  printf "Usage: kalspec [options] [files or directories]\n\n"
  printf "  -s, --spring\t\t\tRun specs using spring (Rails preloader)\n"
  exit
fi

if [ $1 == "--spring" ] || [ $1 == '-s' ]
then
  shift
  spring rspec $@ --format documentation --no-profile
  # spring rspec $@ --format RSpecSay --no-profile
else
  rspec $@ --format documentation --no-profile
  # rspec $@ --format RSpecSay --no-profile
fi

